baseURL = "https://yanael.io/"
languageCode = "en-us"
title = "Yanaël Barbier"
theme = "neutral"

[params]
    description = "I build my path with an export!"
    dateFormatToUse = "2006-01-02"
    replaceGoogleFonts = "fonts.loli.net"
    twitter = "YanaelBarbier"
    github = "https://github.com/st3w4r"

[menu]

  [[menu.main]]
    name = "Main"
    url = "/"
    weight = -100