baseURL = "https://yanael.io/"
languageCode = "en-us"
title = "Yanaël Barbier"
theme = "neutral"

[params]
    subtitle = "I build my path with an export!"
    description = "I build my path with an export!"
    dateFormatToUse = "2006-01-02"
    twitter = "YanaelBarbier"
    github = "https://github.com/st3w4r"
    assetDir = "themes/neutral/assets"

[menu]

  [[menu.main]]
    name = "Main"
    url = "/"
    weight = -100

  [[menu.main]]
    name = "Blog"
    url = "https://moonshot.engineer"
    weight = -95


[outputs]
  home = ["HTML", "RSS"]

[outputFormats.RSS]
  baseName = "rss"
