version: '3'

services:

  build:
    build:
      context: .
      dockerfile: Dockerfile
    command: hugo
    working_dir: "/app"
    volumes:
      - ".:/app"
      - "./public:/app/public"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: hugo server --bind="0.0.0.0" ${OPTIONS}
    working_dir: "/app"
    volumes:
      - ".:/app"
    ports:
      - "1313:1313"
