version: '3'

services:

  build:
    image: klakegg/hugo:0.70.0
    volumes:
      - ".:/src"
      - "./public:/target"

  server:
    image: klakegg/hugo:0.70.0
    command: server
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"
